local songs = {
	{
		title = "Tena ft David - Is You",
		artist = "Tena",
		audioId = "119531967840473",
		BackgroundImage = "99390877644985",
		AlbumImage = "99390877644985",
		lyrics = {
			{time = 0, text = "", duration = 31},
			{time = 1, text = "ក្នុងសមុទ្រមានតែភាពបរិសុទ្ធស្រស់ថ្លា", duration = 9.5},
			{time = 1, text = "ប្រៀបដូចស្នេហាដែលបងមានលើជីវ៉ា", duration = 5.5},
			{time = 1, text = "ធំអស្ចារ្យគ្មានអ្វី​... ប្រៀបស្មើបាន", duration = 11},
			{time = 1, text = "ដៃទាំងពីរអោបអូនគ្រប់ពេលគ្រប់​វិនាទី", duration = 10},
			{time = 1, text = "ចាប់ពីពេលនេះទៅយើ​ង នៅក្បែរគ្នាគ្រប់វេលា", duration = 10},
			{time = 1, text = "ធានាមិនឲ្យអូនឈឺចាប់", duration = 5},
			{time = 1, text = "មិនថាថ្ងៃនេះឬក៏ថ្ងៃស្អែក មិនបែកជីវ៉ា", duration = 6},
			{time = 1, text = "សន្យាថានឹងមើលថែអូន....", duration = 6},
			{time = 1, text = "យើងនឹងកាន់ដៃគ្នាឆ្ពោះទៅរកស្នេហ៍ស្មោះស្ម័គ្រ​ ទោះមានឧបស្ថិត្តក៏មិនបកក្រោយ....", duration = 15}, 
			{time = 1, text = "ក្ដីស្នេហាបងប្រៀបដូចជាសមុទ្រខ្សាច់", duration = 6},
			{time = 1, text = "រាប់ម៉ឺលានគ្រាប់មិនអាចនឹងរាប់បាន", duration = 5}, -- <-- FIXED HERE
			{time = 1, text = "អូនប្រៀបបានព្រះអាទិត្យបំភ្លឺ ជីវិតបង..", duration = 7.5},  
			{time = 1, text = "គឺមានតែនួនល្អងជាដង្ហើមស្នេហ៏....", duration = 5},  
			{time = 1, text = "ទោះបីលើមេឃមានហ្នឹងផ្កាយច្រើនប៉ុណ្ណា​", duration = 6},  
			{time = 1, text = "គឺមានតែមួយដែលបងជ្រើសរើសមកថែរក្សារ​", duration = 5.5},
			{time = 1, text = "គឺរូបអូននេះហើយគឺជាចម្លើយខ្វះមិនបាន", duration = 8},
			{time = 1, text = "ចំណោទស្នេហ៏នេះត្រូវបានបញ្ចប់.... ព្រោះមានអូន", duration = 9},
			{time = 1, text = "ហ៊ូ..... ហ៊ូ..... ហ៊ូ.....", duration = 8},
			{time = 1, text = "សូមចូលDiscordដើម្បីបានបទច្រើនទៀត Karaoke Made By .trebbor & tenzxy", duration = 15},
			{time = 1, text = "ក៏មិនដឹងថាថ្ងៃក្រោយស្នេហាយើងទៅជាបែបណា..", duration = 9},
			{time = 1, text = "សម្រាបថ្ងៃនេះបងសូមមើលថែជីវ៉ា... មិនឲ្យអ្នកណា", duration = 9},
			{time = 1, text = "បំផ្លាញស្នេហាយើងឡើយ...", duration = 5.5},
			{time = 1, text = "មិនថាថ្ងៃនេះឬក៏ថ្ងៃស្អែក មិនបែកជីវ៉ា", duration = 6},
			{time = 1, text = "សន្យាថានឹងមើលថែអូន....", duration = 5.5},
			{time = 1, text = "យើងនឹងកាន់ដៃគ្នាឆ្ពោះទៅរកស្នេហ៍ស្មោះស្ម័គ្រ​ ទោះមានឧបស្ថិត្តក៏មិនបកក្រោយ....", duration = 15}, 
			{time = 1, text = "ក្ដីស្នេហាបងប្រៀបដូចជាសមុទ្រខ្សាច់", duration = 6},
			{time = 1, text = "រាប់ម៉ឺលានគ្រាប់មិនអាចនឹងរាប់បាន", duration = 6},
			{time = 1, text = "អូនប្រៀបបានព្រះអាទិត្យបំភ្លឺ ជីវិតបង..", duration = 8},  
			{time = 1, text = "គឺមានតែនួនល្អងជាដង្ហើមស្នេហ៏....", duration = 6},  
			{time = 1, text = "ទោះបីលើមេឃមានហ្នឹងផ្កាយច្រើនប៉ុណ្ណា​", duration = 5},  
			{time = 1, text = "គឺមានតែមួយដែលបងជ្រើសរើសមកថែរក្សារ​", duration = 6},
			{time = 1, text = "គឺរូបអូននេះហើយគឺជាចម្លើយខ្វះមិនបាន", duration = 6},
			{time = 1, text = "ចំណោទស្នេហ៏នេះត្រូវបានបញ្ចប់.... ព្រោះមានអូន", duration = 5},
			{time = 1, text = "ទោះបីមេឃរលំឬក៏ភ្នំរលាយ​", duration = 6},  
			{time = 1, text = "ក៏ចិត្តមួយនេះមិនចេះរាយម៉ាយក្បត់ស្នេហាឡើយ", duration = 6},  
			{time = 1, text = "អូនប្រៀបបានព្រះអាទិត្យបំភ្លឺ ជីវិតបង..", duration = 8}, 
			{time = 1, text = "គឺមានតែនួនល្អងជាដង្ហើមស្នេហ៏....", duration = 5}, 
			{time = 1, text = "ទោះបីលើមេឃមានហ្វូងផ្កាយច្រើនប៉ុណ្ណា", duration = 5},
			{time = 1, text = "គឺមានតែមួយដែលបងជ្រើសរើសមកថែរក្សា", duration = 5},
			{time = 1, text = "គឺរូបអូននេះហើយគឺជាចម្លើយខ្វះមិនបាន", duration = 7},
			{time = 1, text = "ចំណោទស្នេហ៏នេះត្រូវបានបញ្ចប់.... ព្រោះមានអូន...", duration = 14},
		}
	},
	{
		title = "ខ្មាស់ទេ​..?",
		artist = "Ah Da Sakada Ft Sothea Roth",
		audioId = "107230341344247",
		BackgroundImage = "111872766408155",
		AlbumImage = "111872766408155",
		lyrics = {
			{time = 0, text = "", duration = 13},
			{time = 1, text = "(ប)តើខ្មាស់គេទេ មានសង្សាដូចបង", duration = 3},
			{time = 1, text = "តើខ្មាសគេទេពេលដើរកាន់ដៃបង", duration = 3},
			{time = 1, text = "បងមិនសង្ហារមិនសូវមានទ្រព្យ កម្រជូនអូនទិញរបស់ល្អៗ", duration = 6},
			{time = 1, text = "ខ្មាសមិត្តអូនទេ ពេលដើរលេងម្ដងៗ", duration = 2.5},
			{time = 1, text = "ខ្មាសមិត្តអូនទេ ពេលអង្គុយក្បែលបង", duration = 3},
			{time = 1, text = "ឲ្យបងសុំទោសដែលមកស្គាល់បង ចំពេលដែលបងកុំពុងលំបាក", duration = 6},
			{time = 1, text = "ម្សិលមិញកណ្តាលភ្លៀង លើដងវិថី", duration = 2.7},
			{time = 1, text = "បងសែនអាណិតអូន គ្មានពាក្យនឹងស្តី", duration = 3},
			{time = 1, text = "ខ្លួនប្រាណទទឹកជោក តែអូនថាមិនអី", duration = 3},
			{time = 1, text = "ពិសីអូនញញឺម ជិះអោបចង្កេះបង", duration = 3},
			{time = 1, text = "រឺឯយប់នេះ អូនថាមិនចង់គេង", duration = 3},
			{time = 1, text = "ចង់ស្តាប់សម្លេង ចង់និយាយសារសង", duration = 2.6},
			{time = 1, text = "បើសិនយប់នេះ មានអូនក្បែរបង", duration = 2.5},
			{time = 1, text = "អូហូឡូយហួស មិនដឹងជាល្អយ៉ាងណា", duration = 3},
			{time = 1, text = "ឲ្យតែពេលរាត្រី បងសែនច្រណែននឹងដួងច័ន្ទ", duration = 3},
			{time = 1, text = "ព្រោះនៅក្បែរច័ន្ទ វាតែងតែមានដួងផ្កាយ", duration = 2.7},
			{time = 1, text = "ចង់ឲ្យឆាប់ភ្លឺ ព្រះអាទិត្យបង្ហាញកាយ", duration = 3},
			{time = 1, text = "នៅមិនសុខឡើយ ពេលដែលគ្មានអូនក្បែរ....", duration = 4},
			{time = 1, text = "តើខ្មាស់គេទេ មានសង្សាដូចបង", duration = 3},
			{time = 1, text = "តើខ្មាស់គេទេ ពេលដើរកាន់ដៃបង", duration = 3},
			{time = 1, text = "បងមិនសង្ហារមិនសូវមានទ្រព្យ កម្រជូនអូនទិញរបស់ល្អៗ", duration = 6},
			{time = 1, text = "ខ្មាស់មិត្តអូនទេ ពេលដើរលេងម្តងៗ", duration = 2.5},
			{time = 1, text = "ខ្មាស់មិត្តអូនទេ ពេលអង្គុយក្បែរបង", duration = 3},
			{time = 1, text = "ឲ្យបងសុំទោសដែលមកស្គាល់បង ចំពេលដែលបងកុំពុងលំបាក", duration = 8},
			{time = 1, text = "(ស)មិនខ្មាស់គេទេ មានសង្សាដូចបង", duration = 3},
			{time = 1, text = "មិនខ្មាស់គេទេ ពេលដើរកាន់ដៃបង", duration = 3},
			{time = 1, text = "បងមិនសង្ហាមិនសូវមានទ្រព្យ តែបងស្នេហ៍អូនដោយចិត្តស្មោះសរ", duration = 5.5},
			{time = 1, text = "មិត្តអូនច្រណែន ពេលដើរលេងម្តងៗ", duration = 2.5},
			{time = 1, text = "មិត្តអូនច្រណែន ពេលអង្គុយក្បែរបង", duration = 3},
			{time = 1, text = "គេចង់បានស្នេហ៍ ផ្អែមល្ហែមដូចយើងខំតស៊ូឡើង យើងកុំចុះចាញ់", duration = 6},
			{time = 1, text = "មានសំណាង ជាតិនេះអូនមានសំណាង", duration = 3},
			{time = 1, text = "មានកល្យាណ អូនដូចមានពេជ្រក្នុងដៃ", duration = 3},
			{time = 1, text = "កុំខ្វល់ពីគេ បើបងស្រឡាញ់ស្រីកុំខ្វល់សម្តី ដែលរំខានចិត្តបង", duration =5},
			{time = 1, text = "រាត្រីនេះអូនមិនចង់គេង", duration = 3},
			{time = 1, text = "ចង់ស្តាប់សម្លេង ចង់និយាយសារសង", duration = 3},
			{time = 1, text = "បើសិនពេលនេះ មានបងក្បែរអូន", duration = 3},
			{time = 1, text = "អូហូឡូយហួស មិនដឹងជាល្អយ៉ាងណា", duration = 3},
			{time = 1, text = "ឲ្យតែពេលរាត្រី អូនសែនច្រណែនដួងច័ន្ទ", duration = 3},
			{time = 1, text = "ព្រោះនៅក្បែរច័ន្ទ វាតែងតែមានដួងផ្កាយ", duration = 2.5},
			{time = 1, text = "បន់ឲ្យឆាប់ភ្លឺ ព្រះអាទិត្យបង្ហាញកាយ", duration = 2.5},
			{time = 1, text = "នៅមិនសុខឡើយ ពេលដែលគ្មានបងក្បែរ", duration = 5.5},
			{time = 1, text = "(ប)តើខ្មាស់គេទេ មានសង្សាដូចបង", duration = 3},
			{time = 1, text = "តើខ្មាស់គេទេ ពេលដើរកាន់ដៃបង", duration = 2.5},
			{time = 1, text = "បងមិនសង្ហារមិនសូវមានទ្រព្យ កម្រជូនអូនទិញរបស់ល្អៗ", duration = 5.5},
			{time = 1, text = "ខ្មាស់មិត្តអូនទេ ពេលដើរលេងម្តងៗ", duration = 2.5},
			{time = 1, text = "ខ្មាសមិត្តអូនទេ ពេលអង្គុយក្បែលបង", duration = 3},
			{time = 1, text = "ឲ្យបងសុំទោសដែលមកស្គាល់បង ចំពេលដែលបងកុំពុងលំបាក", duration = 6},
			{time = 1, text = "(ស)មិនខ្មាស់គេទេ មានសង្សាដូចបង", duration = 3},
			{time = 1, text = "មិនខ្មាស់គេទេ ពេលដើរកាន់ដៃបង", duration = 3},
			{time = 1, text = "បងមិនសង្ហាមិនសូវមានទ្រព្យ តែបងស្នេហ៍អូនដោយចិត្តស្មោះសរ", duration = 5.5},
			{time = 1, text = "មិត្តអូនច្រណែន ពេលដើរលេងម្តងៗ", duration = 2.5},
			{time = 1, text = "មិត្តអូនច្រណែន ពេលអង្គុយក្បែរបង", duration = 3},
			{time = 1, text = "គេចង់បានស្នេហ៍ ផ្អែមល្ហែមដូចយើងខំតស៊ូឡើង យើងកុំចុះចាញ់", duration = 6},
		}
	},
	{
		title = "តួរង ស្រឡាញ់គេតែម្នាក់ឯង",
		artist = "Noly Record ft. Heng Pitu",
		audioId = "131820449804350",
		BackgroundImage = "84959488205374",
		AlbumImage = "81266234985784",
		lyrics = {
			{time = 0, text = "", duration = 19 },
			{time = 1, text = "តែងតែល្អនឹងគេមករហូតហើយ", duration = 4.5 },
			{time = 1, text = "នៅតែមិនទាន់ទទួលចម្លើយ", duration = 4.5 },
			{time = 1, text = "អូនក៏ដឹងច្បាស់ បងស្នេហ៍ត្រើនត្រើយ", duration = 4.3 },
			{time = 1, text = "ស្នេហ៍ដល់កម្រិតណា", duration = 3.5 },
			{time = 1, text = "ពេលអូន sad អ្នកណាកំដរអូនយំ", duration = 4 },
			{time = 1, text = "ពេលយំអ្នកណាជូតទឹកនេត្រា", duration = 4 },
			{time = 1, text = "ហេតុអ្វីរំលងមនុស្សក្បែរជីវ៉ា", duration = 4 },
			{time = 1, text = "មានគេពីពេលណាមក", duration = 4 },
			{time = 1, text = "មិនស្នេហ៍ក៏គួរប្រាប់ឲ្យធ្វើចិត្តជាមុន", duration = 4 },
			{time = 1, text = "នេះទុកបងជាទុនកំដរអារម្មណ៍ស្រី", duration = 3.5 },
			{time = 1, text = "សុខៗ show អ្នកថ្មី ទុកបេះដូងបងលើដី", duration = 4 },
			{time = 1, text = "ហើយដើរកាត់រៀងរាល់ថ្ងៃមិនអើពើ", duration = 5.5 },
			{time = 1, text = "ស្រឡាញ់គេតែម្នាក់ឯង", duration = 2 },
			{time = 1, text = "សែនពិបាកណាស់ទៅហើយ", duration = 2 },
			{time = 1, text = "ចុះម្តេចឡើយថែមគេមកធ្វើអ្វី", duration = 3.5 },
			{time = 1, text = "ថែមគេមកបញ្ឈឺបង ឬចង់ឃើញបងក្ស័យ", duration = 4.5 },
			{time = 1, text = "ខំស៊ូរាប់ឆ្នាំគ្មានន័យសម្រាប់អូន", duration = 4 },
			{time = 1, text = "ស្រឡាញ់គេតែម្នាក់ឯង​ក្រែងថ្ងៃណាគេយល់ចិត្ត", duration = 4 },
			{time = 1, text = "តែការពិតគេមិនទុកយើងក្នុងចិត្តឡើយ", duration = 4 },
			{time = 1, text = "គេគ្រាន់តែផ្តល់សង្ឃឹម", duration = 2 },
			{time = 1, text = "ទុកសម្រាប់ផ្លូវក្រោយ", duration = 2 },
			{time = 1, text = "ពេលនេះគេបានជួបគ្នាហើយ", duration = 4 },
			{time = 1, text = "កុំភ្លេចត្រាណត្រើយ បងនៅចាំធ្វើតួរង", duration = 4 },
			{time = 1, text = "", duration = 14 },
			{time = 1, text = "ពេលខ្លះទំនេរមាសមេឲ្យបងជួនទៅមើលកុន", duration = 3 },
			{time = 1, text = "រសៀលមិនទាន់ក៏អស់កម្លាំង", duration = 2.5 },
			{time = 1, text = "ឲ្យបងជួនទៅញ៉ាំអី", duration = 2 },
			{time = 1, text = "មុនពេលចូលគេង", duration = 1 },
			{time = 1, text = "ឲ្យបងកំដរ call ទៅស្រី", duration = 1.5 },
			{time = 1, text = "បើកទូរស័ព្ទចោលរាល់ថ្ងៃ", duration = 2 },
			{time = 1, text = "ធ្វើចឹងធ្វើអី", duration = 1 },
			{time = 1, text = "ឲ្យបងយល់ច្រលំថាពីសីក៏មានចិត្តលើបង", duration = 3 },
			{time = 1, text = "ច្រលំថាអូនស្រឡាញ់បង ច្រលំថាអូនត្រូវការបង", duration = 4 },
			{time = 1, text = "ហើយពេលខ្លះក៏ច្រលំថាអូនកំពុងជាសង្សានឹងបង", duration = 4 },
			{time = 1, text = "មិត្តភក្តិបងបង្អាប់អូននឹងបង", duration = 2.5 },
			{time = 1, text = "ក៏ប៉ុន្តែតួឯកមិនមែនបង", duration = 2 },
			{time = 1, text = "តើបងខុសអ្វីទៅស្នេហ៍ស្នងទើបធ្វើដាក់បងបែបនេះ", duration = 4 },
			{time = 1, text = "មិនស្នេហ៍ក៏គួរប្រាប់ឲ្យធ្វើចិត្តជាមុន", duration = 3.5 },
			{time = 1, text = "នេះទុកបងជាទុនកំដរអារម្មណ៍ស្រី", duration = 3.5 },
			{time = 1, text = "សុខៗ show អ្នកថ្មី ទុកបេះដូងបងលើដី", duration = 4.5 },
			{time = 1, text = "ហើយដើរកាត់រៀងរាល់ថ្ងៃមិនអើពើ", duration = 4 },
			{time = 1, text = "ស្រឡាញ់គេតែម្នាក់ឯង", duration = 3 },
			{time = 1, text = "សែនពិបាកណាស់ទៅហើយ", duration = 3.5 },
			{time = 1, text = "ចុះម្តេចឡើយថែមគេមកធ្វើអ្វី", duration = 3 },
			{time = 1, text = "ថែមគេមកបញ្ឈឺបង ឬចង់ឃើញបងក្ស័យ", duration = 4 },
			{time = 1, text = "ខំស៊ូរាប់ឆ្នាំគ្មានន័យសម្រាប់អូន", duration = 4 },
			{time = 1, text = "ស្រឡាញ់គេតែម្នាក់ឯង​ក្រែងថ្ងៃណាគេយល់ចិត្ត", duration = 4 },
			{time = 1, text = "តែការពិតគេមិនទុកយើងក្នុងចិត្តឡើយ", duration = 4 },
			{time = 1, text = "គេគ្រាន់តែផ្តល់សង្ឃឹមទុកសម្រាប់ផ្លូវក្រោយ", duration = 4 },
			{time = 1, text = "ពេលនេះគេបានជួបគ្នាហើយ", duration = 4 },
			{time = 1, text = "កុំភ្លេចត្រាណត្រើយ", duration = 1 },
			{time = 1, text = "បងនៅចាំធ្វើតួរង", duration = 1 },
			{time = 1, text = "ស្រឡាញ់គេតែម្នាក់ឯង​សែនពិបាក", duration = 3 },
			{time = 1, text = "អ្នកណាខ្លះយល់អារម្មណ៍មួយនេះ", duration = 3 },
			{time = 1, text = "ដែលគេព្រងើយមិនខ្វល់", duration = 2.5 },
			{time = 1, text = "ដកចិត្តមិនរួច បេះដូងស្រឡាញ់អូនសែនងប់ងល់", duration = 4 },
			{time = 1, text = "ដឹងគេមិនខ្វល់តែចិត្តមួយនេះនៅតែព្យាយាម", duration = 3.5 },
			{time = 1, text = "ស្រឡាញ់គេតែម្នាក់ឯង", duration = 1 },
			{time = 1, text = "ក៏ដឹងច្បាស់នៅតែអត់ធ្មត់តស៊ូ", duration = 4 },
			{time = 1, text = "សង្ឃឹមថ្ងៃណាមួយគេនឹងព្រម", duration = 3.5 },
			{time = 1, text = "ទោះយូរប៉ណ្ណា បេះដូងមួយនេះមិនចុះញ៉ម", duration = 4 },
			{time = 1, text = "ចង់នៅក្បែរអូនចង់ជួយមើលថែរូបពៅ", duration = 4 },
			{time = 1, text = "ពេលអូនត្រូវការបង", duration = 1 },
			{time = 1, text = "ស្រឡាញ់គេតែម្នាក់ឯង", duration = 1.5 },
			{time = 1, text = "យល់ច្រលំតែម្នាក់ឯង", duration = 1.5 },
			{time = 1, text = "នៅតែវិលវល់វង្វេង", duration = 2.5 },
			{time = 1, text = "ទោះដឹងថាគេមិនមានចិត្ត", duration = 2.5 },
			{time = 1, text = "ចាត់ទុកថាវាជាកម្មដែលធ្លាប់សាងពីអតីត", duration = 3.5 },
			{time = 1, text = "មកផ្តន្ទាពិតៗ", duration = 3.5 },
			{time = 1, text = "ឲ្យមួយជីវិត", duration = 2 },
			{time = 1, text = "ស្រឡាញ់គេតែម្នាក់ឯង​ ។", duration = 4 }





		}
	},
	{
		title = "Steav Jor",
		artist = "GMENGZ", 
		audioId = "127029682483718", 
		BackgroundImage = "84959488205374", 
		AlbumImage = "84959488205374", 
		lyrics = {
			{time = 0, text = "", duration = 16.5 },
			{time = 1, text = "AYE AYE !!! ", duration = 1 },
			{time = 1, text = "ខ្ញុំមិនមែនមក Diss", duration = 1 },
			{time = 1, text = "តែខ្ញុំចេញមកដាស់", duration = 1.5 },
			{time = 1, text = "ដេញជេីងទាំងក្មេងទាំងចាស់", duration = 1.5 },
			{time = 1, text = "ពួកនេះនៅស្ទេីរ", duration = 1 },
			{time = 1, text = "ពួកនេះនៅស្ទេីរណាស់", duration = 1 },
			{time = 1, text = "ទុកឲខ្ញុំជាអ្នកធ្វេី", duration = 1 },
			{time = 1, text = "ហេីយចាំមេីលឲច្បាស់", duration = 1.5 },
			{time = 1, text = "ខ្ញុំមិនមែនមក Diss", duration = 1 }, 
			{time = 1, text = "តែខ្ញុំចេញមកដាស់", duration = 1.5 },
			{time = 1, text = "ដេញជេីងទាំងក្មេងទាំងចាស់", duration = 1.5 },
			{time = 1, text = "ពួកនេះនៅស្ទេីរ", duration = 1 },
			{time = 1, text = "ពួកនេះនៅស្ទេីរណាស់", duration = 1 },
			{time = 1, text = "ទុកឲខ្ញុំជាអ្នកធ្វេី", duration = 1 },
			{time = 1, text = "ហេីយចាំមេីលឲច្បាស់", duration = 1.5 },
			{time = 1, text = "កេីតតែមួយជាតិ ធាតុតែមួយចាន(ចាន)", duration = 1.5 },
			{time = 1, text = "ខ្ញុំមួយរូបដែលក្នុងចំណោមអ្នកក្លាហាន", duration = 2.5 },
			{time = 1, text = "គ្នានរឿងអ្វីដែលខ្ញុំនេះធ្វេីរវាមិនបាន", duration = 1.5 },
			{time = 1, text = "ធ្វេីរឿងធំដែលអ្នកមិនដែលនឹកស្មាន", duration = 2.5 },
			{time = 1, text = "មកម្ដងហេីយខ្ញុំនៅតែមកម្ដងទៀត", duration = 2.5 },
			{time = 1, text = "ធ្វេីច្រេីនហេីយខ្ញុំនៅតែធ្វេីតទៀត", duration = 1.5 },
			{time = 1, text = "ពេលនេះចេញមកដេញ", duration = 1 },
			{time = 1, text = "ចេញមកដាក់សម្ពាធ", duration = 1 },
			{time = 1, text = "ឡេីងមកវៃលេីរេញយេីងបញ្ចេញគ្រប់ស្នៀត", duration = 2.5 },
			{time = 1, text = "STRAIGHT FROM DA BLOCK", duration = 1 },
			{time = 1, text = "ប៉ះខ្ញុំអ្នកដឹងតែឆក់", duration = 0.5 },
			{time = 1, text = "Im on the top ដេករាប់តែលុយកក់", duration = 2 },
			{time = 1, text = "ពួកអាអ្នកស្អប់ឃេីញហេីយឈរសម្លក់", duration = 2.5 },
			{time = 1, text = "បានត្រឹមតែសម្លឹងមិនបានមួយចំណិតត្រសក់", duration = 2.5 },
			{time = 1, text = "ក្មេងខ្ញុំប្រហេីនអោយតែហ៊ានបាស់ជេីង", duration = 1.5 },
			{time = 1, text = "តេីអ្នកណាហ៊ានផ្គេីនឲនាក់ឯងបះសក់", duration = 2 },
			{time = 1, text = "មាត់ឡេីងកម្ដៅព្រុះពាក្យដូចជាភ្លេីង", duration = 2.5 },
			{time = 1, text = "តេីអ្នកណាចិត្តសឿងចង់លេង ឬ ចង់ក្ដក់ ?", duration = 2.5 },
			{time = 1, text = "ចង់លេង ឬ ចង់ក្ដក់ ?", duration = 2 },
			{time = 1, text = "ចង់លេង ឬ ចង់ក្ដក់ ?", duration = 1.5 },
			{time = 1, text = "តេីអ្នកណាចិត្តសឿងចង់លេង ឬ ចង់ក្ដក់ ?", duration = 2.5 },
			{time = 1, text = "ចង់លេង ឬ ចង់ក្ដក់ ?", duration = 2 },
			{time = 1, text = "ចង់លេង ឬ ចង់ក្ដក់ ?", duration = 2 },
			{time = 1, text = "ចង់លេង ឬ ចង់ក្ដក់ ?", duration = 1.5 },
			{time = 1, text = "តេីអ្នកណាចិត្តសឿងចង់លេង ឬ ចង់ក្ដក់ ?", duration = 2.5 },
			{time = 1, text = "AYE AYE !!!", duration = 1.8 },
			{time = 1, text = "ខ្ញុំមិនមែនមក Diss", duration = 1 }, 
			{time = 1, text = "តែខ្ញុំចេញមកដាស់", duration = 1.5 },
			{time = 1, text = "ដេញជេីងទាំងក្មេងទាំងចាស់", duration = 1.5 },
			{time = 1, text = "ពួកនេះនៅស្ទេីរ", duration = 1 },
			{time = 1, text = "ពួកនេះនៅស្ទេីរណាស់", duration = 1 },
			{time = 1, text = "ទុកឲខ្ញុំជាអ្នកធ្វេី", duration = 1 },
			{time = 1, text = "ហេីយចាំមេីលឲច្បាស់", duration = 0.9 },
			{time = 1, text = "ខ្ញុំមិនមែនមក Diss", duration = 1 }, 
			{time = 1, text = "តែខ្ញុំចេញមកដាស់", duration = 1.5 },
			{time = 1, text = "ដេញជេីងទាំងក្មេងទាំងចាស់", duration = 1.5 },
			{time = 1, text = "ពួកនេះនៅស្ទេីរ", duration = 1 },
			{time = 1, text = "ពួកនេះនៅស្ទេីរណាស់", duration = 1 },
			{time = 1, text = "ទុកឲខ្ញុំជាអ្នកធ្វេី", duration = 1 },
			{time = 1, text = "ហេីយចាំមេីលឲច្បាស់", duration = 0.9 },
			{time = 1, text = "ពេលខ្លះមិនចង់ថា ពេលខ្លះមិនចង់ឃេីញ", duration = 2 },
			{time = 1, text = "ហេីយពេលខ្លះមិនចង់ដឹង ពេលខ្លះមិនចង់ឮ", duration = 2 },
			{time = 1, text = "អត់សូវចេះរណបវាយអែបសុីអប", duration = 1.5 },
			{time = 1, text = "តែពេលពួកវាដាច់របបវាមកថាយេីងឌឺ", duration = 2.5 },
			{time = 1, text = "ហេីយនេះគឺជាសំឡេងក្មេងដែលឡេីង Rank", duration = 2.2 },
			{time = 1, text = "ងេីបទៅផ្សងព្រេងទាំងមុនមេឃភ្លឺ", duration = 2.3 },
			{time = 1, text = "ឃេីញពួកខ្ញុំវាឡេីងនូវហាងឆេង", duration = 1.5 },
			{time = 1, text = "បេីសិនគេចង់មកលេងថាខ្ញុំនេះមិនដែលព្រឺ", duration = 2.5 },
			{time = 1, text = "STRAIGHT FROM DA BLOCK", duration = 1 },
			{time = 1, text = "ប៉ះខ្ញុំអ្នកដឹងតែឆក់", duration = 0.8 },
			{time = 1, text = "ដេីរមកផ្លូវឆ្ងាយ yeah,", duration = 1.2 },
			{time = 1, text = "I walk how i talk", duration = 1 },
			{time = 1, text = "ខ្ញុំមិនសុីទេសាច់ដែលគេបង្កក", duration = 2 },
			{time = 1, text = "គ្នាខ្ញុំដូចចចកយើង​សុីតែសាច់ច្រឡក", duration = 2.3 },
			{time = 1, text = "Came a long way", duration = 1 },
			{time = 1, text = "ថាខ្ញុំនេះមិនអាចនឹងបក", duration = 1.5 },
			{time = 1, text = "ខ្ញុំដេកគិត គុណ ចែក បូក ដក", duration = 2 },
			{time = 1, text = "អាណាពិតហេីយអាណាគេចង់សក", duration = 2 },
			{time = 1, text = "ខ្ញុំឲវាឈឺចិត្តបេីសិនវាមកចង់ក្អក", duration = 2 },
			{time = 1, text = "ព្រោះពួកវានៅភ្លេី នៅស្ទេីរ នៅខ្លៅ", duration = 2 },
			{time = 1, text = "ពួកអាខ្មោចឆៅចង់មកប៉ះគ្រូម៉ៅ", duration = 2 },
			{time = 1, text = "អោយឯងដេកអៀចដល់ល្ងាចថ្ងៃច័ន្ទ", duration = 2 },
			{time = 1, text = "ថ្ងៃអង្គារ ថ្ងៃពុធ ថ្ងៃព្រហស្បតិ៍ សុក្រ សៅរ៏", duration = 2 },
			{time = 1, text = "ពួកអាត្រីផ្ទក់វាមិនស្គាល់ភ្លេីងក្ដៅ", duration = 2 },
			{time = 1, text = "ចាប់វាយកទៅស្ងោជ្រក់ឬ ក៏វះងៀតឆៅ", duration = 2 },
			{time = 1, text = "ធ្វេីឲខ្ញុំនេះមួម៉ៅចិត្តដូចឡេីងកម្ដៅ", duration = 2 },
			{time = 1, text = "ពេលនេះចង់និយាយថា", duration = 1.5 },
			{time = 1, text = "ពួកអាខ្លះចង់ស្ទាវតែពួកអាហ្នឹងស្ទាវជ័រ", duration = 2 },
			{time = 1, text = "GANG មកពីខាងណាអត់ដែលស្គាល់", duration = 2 },
			{time = 1, text = "គ្នាពួកបងប្រេីតែដៃដោះទាល់", duration = 2 },
			{time = 1, text = "ពួកអាក្មេងលេងដីកុំមកចង់ប៉ះពាល់", duration = 2 },
			{time = 1, text = "ពួកអាខ្លះចង់ស្ទាវតែពួកអាហ្នឹងស្ទាវជ័រ", duration = 2.5 },
			{time = 1, text = "GANG មកពីខាងណាអត់ដែលស្គាល់", duration = 2 },
			{time = 1, text = "គ្នាពួកបងប្រេីតែដៃដោះទាល់", duration = 2 },
			{time = 1, text = "ពួកអាក្មេងលេងដីកុំមកចង់ប៉ះពាល់", duration = 2 },
			{time = 1, text = "មានកម្លាំងដូចតោតាំងពីនៅតេះតាស់", duration = 2 },
			{time = 1, text = "អាវយឺតខោសំយេះពាក់កាស", duration = 2 },
			{time = 1, text = "ឈានជេីងចុះមកពីលេី G CLASS", duration = 2 },
			{time = 1, text = "Call ហៅគ្នាតោះទៅក្លិបស្ដាប់បាស", duration = 2 },
			{time = 1, text = "ចាយលុយថ្មីខ្ញុំមិនចាយលុយចាស់", duration = 2 },
			{time = 1, text = "NEW  DIAMOND CHAIN លុយខ្ញុំចូលក្រាស់ៗ", duration = 2.3 },
			{time = 1, text = "នៅក្មេងតែគំនិតខ្ញុំចាស់", duration = 1.8 },
			{time = 1, text = "ចេញដេីរផ្សងព្រេងខ្ញុំមិនដេីរផ្តេសផ្ដាស", duration = 2.5 },
			{time = 1, text = "ខ្ញុំមិនមែនមក Diss តែខ្ញុំចេញមកដាស់", duration = 2.5 },
			{time = 1, text = "ដេញជេីងទាំងក្មេងទាំងចាស់", duration = 1.5 },
			{time = 1, text = "ពួកនេះនៅស្ទេីរពួកនេះនៅស្ទេីរណាស់", duration = 2 },
			{time = 1, text = "ទុកឲខ្ញុំជាអ្នកធ្វេីហេីយចាំមេីលឲច្បាស់", duration = 2.5 },
			{time = 1, text = "ខ្ញុំមិនមែនមក Diss តែខ្ញុំចេញមកដាស់", duration = 2.5 },
			{time = 1, text = "ដេញជេីងទាំងក្មេងទាំងចាស់", duration = 1.5 },
			{time = 1, text = "ពួកនេះនៅស្ទេីរពួកនេះនៅស្ទេីរណាស់", duration = 2 },
			{time = 1, text = "ទុកឲខ្ញុំជាអ្នកធ្វេីហេីយចាំមេីលឲច្បាស់", duration = 2.5 },
		}
	},
	{
		title = "សម្តេចពុកលោកសែនល្អកីឡាករឆ្នើម",
		artist = "ឌៀប សិដ្ឋសុធា",
		audioId = "106230712829282",
		BackgroundImage = "84959488205374",
		AlbumImage = "81266234985784",
		lyrics = {
			{time = 0, text = "", duration = 10 },
			{time = 1, text = "សម្ដេចពុកលោកវាយកូនហ្គោល", duration = 2.5 },
			{time = 1, text = "ស៊ុតឡូបញ្ចូលពូកែខ្លាំងណាស់", duration = 2.5 },
			{time = 1, text = "ទិចនិចពិតជាត្រង់ច្បាស់", duration = 3 },
			{time = 1, text = "ទឹកដៃជើងចាស់រហ័សរហួន", duration = 3 },
			{time = 1, text = "ទិចនិចពិតជាត្រង់ច្បាស់", duration = 2.5 },
			{time = 1, text = "ទឹកដៃជើងចាស់រហ័សរហួន", duration = 3 },
			{time = 1, text = "រាងកាយដងខ្លួន", duration = 2.5 },
			{time = 1, text = "សង្ហារសមសួន", duration = 2.5 },
			{time = 1, text = "កម្លាំងពលំមាំមួន", duration = 3 },
			{time = 1, text = "សែនឈ្នះផ្ទួនៗគ្រប់វិញ្ញាសារ", duration = 3 },
			{time = 1, text = "បន្ទាប់ពីកិច្ចការងារជាតិ", duration = 3 },
			{time = 1, text = "សម្ដេចពុកឆ្លៀតតែងតែហាត់ប្រាណ", duration = 3 },
			{time = 1, text = "លេងកីឡាជាការកំសាន្ត", duration = 2.5 },
			{time = 1, text = "នាពេលស្រាកស្រាន្តបានអារម្មណ៍ស្រស់ថ្លា", duration = 3 },
			{time = 1, text = "លេងកីឡាជាការកំសាន្ត", duration = 2.5 },
			{time = 1, text = "នាពេលស្រាកស្រាន្តបានអារម្មណ៍ស្រស់ថ្លា", duration = 3 },
			{time = 1, text = "ពុកសែនសង្ហារ ×២", duration = 5.5 },
			{time = 1, text = "ទាំងកាយទាំងចិត្តវាចារ", duration = 2.5 },
			{time = 1, text = "កម្លាំងខ្លាំងក្លាមានសុខភាពល្អ", duration = 3 },
			{time = 1, text = "ព្រះជន្មលោកពុកច្រើនហើយ", duration = 3 },
			{time = 1, text = "ថាមពលនៅឡើយ", duration = 2 },
			{time = 1, text = "ដូចជាយុវវ័យ", duration = 2 },
			{time = 1, text = "អង់អាចប្រាជ្ញាវាងវៃ", duration = 2.5 },
			{time = 1, text = "កម្រិតថ្វីដៃជាកីឡាករ", duration = 2.5 },
			{time = 1, text = "អង់អាចប្រាជ្ញាវាងវៃ", duration = 2.5 },
			{time = 1, text = "កម្រិតថ្វីដៃជាកីឡាករ", duration = 2.5 },
			{time = 1, text = "សូមព្រះឥន្ទ្រប្រទានពរ ទេវតាបាចផ្កាសាទរ", duration = 6.5 },
			{time = 1, text = "ស្តេចពុកមានសុខភាពល្អ", duration = 2.5 },
			{time = 1, text = "បន្តរដឺកនាំជាតិកម្ពុជា", duration = 2.5 },
			{time = 1, text = "", duration = 29 },






		}
	},
    	{
		title = "Steav Jor",
		artist = "GMENGZ", 
		audioId = "127029682483718", 
		BackgroundImage = "84959488205374", 
		AlbumImage = "84959488205374", 
		lyrics = {
			{time = 0, text = "", duration = 17 },
			{time = 1, text = "AYE AYE !!! ", duration = 1.5 },
			{time = 1, text = "ខ្ញុំមិនមែនមក Diss", duration = 1 },
			{time = 1, text = "តែខ្ញុំចេញមកដាស់", duration = 1.5 },
			{time = 1, text = "ដេញជេីងទាំងក្មេងទាំងចាស់", duration = 1.5 },
			{time = 1, text = "ពួកនេះនៅស្ទេីរ", duration = 1 },
			{time = 1, text = "ពួកនេះនៅស្ទេីរណាស់", duration = 1 },
			{time = 1, text = "ទុកឲខ្ញុំជាអ្នកធ្វេី", duration = 1 },
			{time = 1, text = "ហេីយចាំមេីលឲច្បាស់", duration = 1.5 },
			{time = 1, text = "ខ្ញុំមិនមែនមក Diss", duration = 1 }, 
			{time = 1, text = "តែខ្ញុំចេញមកដាស់", duration = 1.5 },
			{time = 1, text = "ដេញជេីងទាំងក្មេងទាំងចាស់", duration = 1.5 },
			{time = 1, text = "ពួកនេះនៅស្ទេីរ", duration = 1 },
			{time = 1, text = "ពួកនេះនៅស្ទេីរណាស់", duration = 1 },
			{time = 1, text = "ទុកឲខ្ញុំជាអ្នកធ្វេី", duration = 1 },
			{time = 1, text = "ហេីយចាំមេីលឲច្បាស់", duration = 1.5 },
			{time = 1, text = "កេីតតែមួយជាតិ ធាតុតែមួយចាន(ចាន)", duration = 1.5 },
			{time = 1, text = "ខ្ញុំមួយរូបដែលក្នុងចំណោមអ្នកក្លាហាន", duration = 2.5 },
			{time = 1, text = "គ្នានរឿងអ្វីដែលខ្ញុំនេះធ្វេីរវាមិនបាន", duration = 1.5 },
			{time = 1, text = "ធ្វេីរឿងធំដែលអ្នកមិនដែលនឹកស្មាន", duration = 2.5 },
			{time = 1, text = "មកម្ដងហេីយខ្ញុំនៅតែមកម្ដងទៀត", duration = 2.5 },
			{time = 1, text = "ធ្វេីច្រេីនហេីយខ្ញុំនៅតែធ្វេីតទៀត", duration = 1.5 },
			{time = 1, text = "ពេលនេះចេញមកដេញ", duration = 1 },
			{time = 1, text = "ចេញមកដាក់សម្ពាធ", duration = 1 },
			{time = 1, text = "ឡេីងមកវៃលេីរេញយេីងបញ្ចេញគ្រប់ស្នៀត", duration = 2.5 },
			{time = 1, text = "STRAIGHT FROM DA BLOCK", duration = 1 },
			{time = 1, text = "ប៉ះខ្ញុំអ្នកដឹងតែឆក់", duration = 0.5 },
			{time = 1, text = "Im on the top ដេករាប់តែលុយកក់", duration = 2 },
			{time = 1, text = "ពួកអាអ្នកស្អប់ឃេីញហេីយឈរសម្លក់", duration = 2.5 },
			{time = 1, text = "បានត្រឹមតែសម្លឹងមិនបានមួយចំណិតត្រសក់", duration = 2.5 },
			{time = 1, text = "ក្មេងខ្ញុំប្រហេីនអោយតែហ៊ានបាស់ជេីង", duration = 1.5 },
			{time = 1, text = "តេីអ្នកណាហ៊ានផ្គេីនឲនាក់ឯងបះសក់", duration = 2 },
			{time = 1, text = "មាត់ឡេីងកម្ដៅព្រុះពាក្យដូចជាភ្លេីង", duration = 2.5 },
			{time = 1, text = "តេីអ្នកណាចិត្តសឿងចង់លេង ឬ ចង់ក្ដក់ ?", duration = 2.5 },
			{time = 1, text = "ចង់លេង ឬ ចង់ក្ដក់ ?", duration = 2 },
			{time = 1, text = "ចង់លេង ឬ ចង់ក្ដក់ ?", duration = 1.5 },
			{time = 1, text = "តេីអ្នកណាចិត្តសឿងចង់លេង ឬ ចង់ក្ដក់ ?", duration = 2.5 },
			{time = 1, text = "ចង់លេង ឬ ចង់ក្ដក់ ?", duration = 2 },
			{time = 1, text = "ចង់លេង ឬ ចង់ក្ដក់ ?", duration = 2 },
			{time = 1, text = "ចង់លេង ឬ ចង់ក្ដក់ ?", duration = 1.5 },
			{time = 1, text = "តេីអ្នកណាចិត្តសឿងចង់លេង ឬ ចង់ក្ដក់ ?", duration = 2.5 },
			{time = 1, text = "AYE AYE !!!", duration = 1.8 },
			{time = 1, text = "ខ្ញុំមិនមែនមក Diss", duration = 1 }, 
			{time = 1, text = "តែខ្ញុំចេញមកដាស់", duration = 1.5 },
			{time = 1, text = "ដេញជេីងទាំងក្មេងទាំងចាស់", duration = 1.5 },
			{time = 1, text = "ពួកនេះនៅស្ទេីរ", duration = 1 },
			{time = 1, text = "ពួកនេះនៅស្ទេីរណាស់", duration = 1 },
			{time = 1, text = "ទុកឲខ្ញុំជាអ្នកធ្វេី", duration = 1 },
			{time = 1, text = "ហេីយចាំមេីលឲច្បាស់", duration = 0.9 },
			{time = 1, text = "ខ្ញុំមិនមែនមក Diss", duration = 1 }, 
			{time = 1, text = "តែខ្ញុំចេញមកដាស់", duration = 1.5 },
			{time = 1, text = "ដេញជេីងទាំងក្មេងទាំងចាស់", duration = 1.5 },
			{time = 1, text = "ពួកនេះនៅស្ទេីរ", duration = 1 },
			{time = 1, text = "ពួកនេះនៅស្ទេីរណាស់", duration = 1 },
			{time = 1, text = "ទុកឲខ្ញុំជាអ្នកធ្វេី", duration = 1 },
			{time = 1, text = "ហេីយចាំមេីលឲច្បាស់", duration = 0.9 },
			{time = 1, text = "ពេលខ្លះមិនចង់ថា ពេលខ្លះមិនចង់ឃេីញ", duration = 2 },
			{time = 1, text = "ហេីយពេលខ្លះមិនចង់ដឹង ពេលខ្លះមិនចង់ឮ", duration = 2 },
			{time = 1, text = "អត់សូវចេះរណបវាយអែបសុីអប", duration = 1.5 },
			{time = 1, text = "តែពេលពួកវាដាច់របបវាមកថាយេីងឌឺ", duration = 2.5 },
			{time = 1, text = "ហេីយនេះគឺជាសំឡេងក្មេងដែលឡេីង Rank", duration = 2.2 },
			{time = 1, text = "ងេីបទៅផ្សងព្រេងទាំងមុនមេឃភ្លឺ", duration = 2.3 },
			{time = 1, text = "ឃេីញពួកខ្ញុំវាឡេីងនូវហាងឆេង", duration = 1.5 },
			{time = 1, text = "បេីសិនគេចង់មកលេងថាខ្ញុំនេះមិនដែលព្រឺ", duration = 2.5 },
			{time = 1, text = "STRAIGHT FROM DA BLOCK", duration = 1 },
			{time = 1, text = "ប៉ះខ្ញុំអ្នកដឹងតែឆក់", duration = 0.8 },
			{time = 1, text = "ដេីរមកផ្លូវឆ្ងាយ yeah,", duration = 1.2 },
			{time = 1, text = "I walk how i talk", duration = 1 },
			{time = 1, text = "ខ្ញុំមិនសុីទេសាច់ដែលគេបង្កក", duration = 2 },
			{time = 1, text = "គ្នាខ្ញុំដូចចចកយើង​សុីតែសាច់ច្រឡក", duration = 2.3 },
			{time = 1, text = "Came a long way", duration = 1 },
			{time = 1, text = "ថាខ្ញុំនេះមិនអាចនឹងបក", duration = 1.5 },
			{time = 1, text = "ខ្ញុំដេកគិត គុណ ចែក បូក ដក", duration = 2 },
			{time = 1, text = "អាណាពិតហេីយអាណាគេចង់សក", duration = 2 },
			{time = 1, text = "ខ្ញុំឲវាឈឺចិត្តបេីសិនវាមកចង់ក្អក", duration = 2 },
			{time = 1, text = "ព្រោះពួកវានៅភ្លេី នៅស្ទេីរ នៅខ្លៅ", duration = 2 },
			{time = 1, text = "ពួកអាខ្មោចឆៅចង់មកប៉ះគ្រូម៉ៅ", duration = 2 },
			{time = 1, text = "អោយឯងដេកអៀចដល់ល្ងាចថ្ងៃច័ន្ទ", duration = 2 },
			{time = 1, text = "ថ្ងៃអង្គារ ថ្ងៃពុធ ថ្ងៃព្រហស្បតិ៍ សុក្រ សៅរ៏", duration = 2 },
			{time = 1, text = "ពួកអាត្រីផ្ទក់វាមិនស្គាល់ភ្លេីងក្ដៅ", duration = 2 },
			{time = 1, text = "ចាប់វាយកទៅស្ងោជ្រក់ឬ ក៏វះងៀតឆៅ", duration = 2 },
			{time = 1, text = "ធ្វេីឲខ្ញុំនេះមួម៉ៅចិត្តដូចឡេីងកម្ដៅ", duration = 2 },
			{time = 1, text = "ពេលនេះចង់និយាយថា", duration = 1.5 },
			{time = 1, text = "ពួកអាខ្លះចង់ស្ទាវតែពួកអាហ្នឹងស្ទាវជ័រ", duration = 2 },
			{time = 1, text = "GANG មកពីខាងណាអត់ដែលស្គាល់", duration = 2 },
			{time = 1, text = "គ្នាពួកបងប្រេីតែដៃដោះទាល់", duration = 2 },
			{time = 1, text = "ពួកអាក្មេងលេងដីកុំមកចង់ប៉ះពាល់", duration = 2 },
			{time = 1, text = "ពួកអាខ្លះចង់ស្ទាវតែពួកអាហ្នឹងស្ទាវជ័រ", duration = 2.5 },
			{time = 1, text = "GANG មកពីខាងណាអត់ដែលស្គាល់", duration = 2 },
			{time = 1, text = "គ្នាពួកបងប្រេីតែដៃដោះទាល់", duration = 2 },
			{time = 1, text = "ពួកអាក្មេងលេងដីកុំមកចង់ប៉ះពាល់", duration = 2 },
			{time = 1, text = "មានកម្លាំងដូចតោតាំងពីនៅតេះតាស់", duration = 2 },
			{time = 1, text = "អាវយឺតខោសំយេះពាក់កាស", duration = 2 },
			{time = 1, text = "ឈានជេីងចុះមកពីលេី G CLASS", duration = 2 },
			{time = 1, text = "Call ហៅគ្នាតោះទៅក្លិបស្ដាប់បាស", duration = 2 },
			{time = 1, text = "ចាយលុយថ្មីខ្ញុំមិនចាយលុយចាស់", duration = 2 },
			{time = 1, text = "NEW  DIAMOND CHAIN លុយខ្ញុំចូលក្រាស់ៗ", duration = 2.3 },
			{time = 1, text = "នៅក្មេងតែគំនិតខ្ញុំចាស់", duration = 1.8 },
			{time = 1, text = "ចេញដេីរផ្សងព្រេងខ្ញុំមិនដេីរផ្តេសផ្ដាស", duration = 2.5 },
			{time = 1, text = "ខ្ញុំមិនមែនមក Diss តែខ្ញុំចេញមកដាស់", duration = 2.5 },
			{time = 1, text = "ដេញជេីងទាំងក្មេងទាំងចាស់", duration = 1.5 },
			{time = 1, text = "ពួកនេះនៅស្ទេីរពួកនេះនៅស្ទេីរណាស់", duration = 2 },
			{time = 1, text = "ទុកឲខ្ញុំជាអ្នកធ្វេីហេីយចាំមេីលឲច្បាស់", duration = 2.5 },
			{time = 1, text = "ខ្ញុំមិនមែនមក Diss តែខ្ញុំចេញមកដាស់", duration = 2.5 },
			{time = 1, text = "ដេញជេីងទាំងក្មេងទាំងចាស់", duration = 1.5 },
			{time = 1, text = "ពួកនេះនៅស្ទេីរពួកនេះនៅស្ទេីរណាស់", duration = 2 },
			{time = 1, text = "ទុកឲខ្ញុំជាអ្នកធ្វេីហេីយចាំមេីលឲច្បាស់", duration = 2.5 },
		}
	},

}

return songs
